name: Code Review

permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: Chinese
          OPENAI_API_ENDPOINT: <https://api.openai.com/v1>
          MODEL:
          top_p: 1
          temperature: 1
- name: Super-Linter
  # You may pin to the exact commit or the version.
  # uses: super-linter/super-linter@3213b9ea991e2d45d760ea8a76aaebad8a2bdb1a
  uses: super-linter/super-linter@v5.4.0
