name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: AI Code Review Action
        uses: freeedcom/ai-codereviewer@v2.4.1
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: AI Code Reviewer
        uses: amit-kumar56/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
